- name: play variables
  hosts: local
  connection: local
  vars:
    COURSE: devops with AWS
    DURATION: 10hrs
    INSTRUCTUR: sivakumar
  tasks:
    - name: variables
      ansible.builtin.debug:
        msg: " This is a full time {{ COURSE }} , with {{ DURATION }} duration, teaching by {{ INSTRUCTUR }} "
