- name: variables in files
  hosts: local
  connection: local
  vars_files:
    - saperate-vars.yaml
  tasks:
    - name: variables from files
      ansible.builtin.debug:
        msg: " This is a full time {{ COURSE }} , with {{ DURATION }} duration, teaching by {{ INSTRUCTOR }} "
