- name: data types
  hosts: local
  connection: local
  vars: 
    DURATION: 120
    COURSE: "DevOps" 
    IS_LIVE: true
    Tools:
      - Ansible
      - Terraform
      - Docker
    CONCEPTS: 
      CI: jenkins
      SCRIPTING: "shell, Ansible, python"
  tasks: 
    - name: display course details
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Live: {{ IS_LIVE }}, Tools: {{ Tools }}, Concept are : - {{ CONCEPTS }}"       