- name: install packages
  hosts: frontend
  become: yes
  tasks:
    ansible.builtin.debug:
    - name: installing {{ item }}
      state: installed
    loop: 
      - nginx
      - git
      - curl  