- name: install packages
  hosts: frontend
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.debug:
        name: "installing {{ item }}"
        state: installed
      loop: 
      - nginx
      - git
      - curl  