- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, suresh, raghava, dileep"
  tasks:
    - name: functions
      ansible.builtin.debug:
        msg: "hello {{ persons }}"

    - name: functions
      ansible.builtin.debug:
        msg: "hello {{ persons | split(',') }}"

    - name: convert map into list 
      vars: 
        course: 
          name: ansible 
          duration: 120hrs 
          trainer: sivekumar
      ansible.builtin.debug:
        msg: "course info: {{ course | dict2items }}"


    - name: convert list into map
      vars: 
        course: 
          - {'key': 'name', 'value': 'ansible'}
          - {'key': 'duration', 'value': '120hrs'}
          - {'key': 'trainer', 'value': 'sivekumar'}
      ansible.builtin.debug:
        msg: "course info: {{ course | items2dict }}"  

    - name: check valid ipaddress or not
      vars: 
        ip: "300.567.980.789"
      ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}"        