- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, suresh, raghava, dileep"
  tasks:
    - name: functions
      ansible.builtin.debug:
        msg: "hello {{ persons }}"

    - name: functions
      ansible.builtin.debug:
        msg: "hello {{ persons | split(',') }}"
